# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

regmatch <- function(m, x, delim) {
    .Call(`_actuary_regmatch`, m, x, delim)
}

spl_prm_cnt <- function(x, n) {
    .Call(`_actuary_spl_prm_cnt`, x, n)
}

